### ISSUE TITLE
Steps with several @process are not documented as being part of them

### ISSUE THREAD

**Issue by benoitdevos** [pousse-cafe/pousse-cafe#114]
According to [documentation](http://www.pousse-cafe-framework.org/doc/reference-guide/#generating-ddd-documentation), a step can be involved in one or more process(es). This is documented with the tag `@process`.
This is not stated in the doc, but the order of the tags `@process` has an impact on the generated doc., i.e. only the first process seems to be correctly output to pdf and html.

Steps to reproduce:
* Generate the doc for the shop app.
* Swap the 2 tags `@process` in the aggregate `Order`:
```java
    /**
     * @process OrderSettlement
     * @process Messaging
     * @event OrderSettled
     */
    @MessageListener(runner = SettleRunner.class)
    public void settle(SettleOrder command) {...}
```
* Generate again the doc, and see the difference.

**Comment by benoitdevos** [comment]
@gdethier This probably comes from the class `ProcessStepDocExtractor`, where only the first `@process`  is processed:
```java
    private Optional<String> processName(ExecutableElement methodDoc) {
        TypeElement containingClass = (TypeElement) methodDoc.getEnclosingElement();
        List<String> processNames = annotationsResolver.process(methodDoc);
        if(domainProcessDocFactory.isDomainProcessDoc(containingClass)) {
            return Optional.of(domainProcessDocFactory.name(containingClass));
        } else if(!processNames.isEmpty()) {
            return Optional.of(processNames.get(0));
        } else {
            return Optional.empty();
        }
    }
```

**Comment by gdethier** [comment]
@benoitdevos Indeed. Looks like you found a bug. :-)

**Comment by gdethier** [comment]
Should be fixed by 482cbe49e869581edb3be556599bd6501b117fd2.

**Comment by gdethier** [comment]
@benoitdevos can you try again with maven plugin 0.14.0-SNAPSHOT? Normally, it should be fixed.

**Comment by benoitdevos** [comment]
> @benoitdevos can you try again with maven plugin 0.14.0-SNAPSHOT? Normally, it should be fixed.

Yes, if you merge this PR https://github.com/pousse-cafe/pousse-cafe-maven-plugin/pull/2

**Comment by gdethier** [comment]
@benoitdevos indeed, done. Thanks!
